apiVersion: apps/v1
kind: Deployment
metadata:
  name: donations-site
  namespace: default
  labels:
    app: donations-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donations-site
  template:
    metadata:
      labels:
        app: donations-site
    spec:
      containers:
      - name: flask-app
        image: ghcr.io/rfxtech/donations-site:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /data
          name: app-data
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: donations-permanent-pvc
